package me.zd12.phantomtools.commands;

import me.zd12.phantomtools.messages;
import net.pravian.bukkitlib.command.BukkitCommand;
import net.pravian.bukkitlib.command.CommandPermissions;
import net.pravian.bukkitlib.command.SourceType;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;

@CommandPermissions(source = SourceType.ANY, permission = "phantom.user.pcc")
public class Command_pcc extends BukkitCommand {   

    @Override
    public boolean run(CommandSender sender, Command cmd, String commandLabel, String[] args) {
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(ChatColor.RED + " ");
        sender.sendMessage(messages.pname + "You have cleared your chat!");
        return true;
    
    }
}
