package me.zd12.phantomtools.commands;

import me.zd12.phantomtools.messages;
import net.pravian.bukkitlib.command.BukkitCommand;
import net.pravian.bukkitlib.command.CommandPermissions;
import net.pravian.bukkitlib.command.SourceType;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;

@CommandPermissions(source = SourceType.ANY, permission = "phantom.ops.cc")
public class Command_cc extends BukkitCommand {   
    
    @Override
    public boolean run(CommandSender sender, Command cmd, String commandLabel, String[] args) {
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(ChatColor.RED + " ");
        Bukkit.broadcastMessage(messages.pname + sender.getName()+ " cleared global chat");
        return true;
    
    }
}
