name: PhantomToolsPlus
main: me.zd12.phantomtools.PhantomTools
version: 0.1

commands:
    pcc:
        usage: /<command>
        description: Clear your personal chat.
    staff:
        usage: /<command>
        description: Check the LulzCraft Staff Team.
    cc:
        usage: /<command>
        description: Clear the servers chat.
    forum:
        usage: /<command>
        description: Check link for the forums.
    warn:
        usage: /<command>
        description: Warn a player
    phantomtools:
        usage: /<command>
        description: Provide information regarding Phantomtools+
    colors:
        usage: /<command>
        description: Provide information about Minecraft colors.
        aliases: colors
    admininfo:
        usage: /<command>
        description: How to obtain administrator.
        aliases: ai
    soon:
        usage: /<command>
        description: Explain what's planned for PhantomTools+
